# Generated by Django 3.2 on 2022-01-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobname_catag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='jobcatag',
            name='catag',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='jobname',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companydetails')),
            ],
        ),
    ]
