# Generated by Django 3.2 on 2022-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220103_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='desc',
            field=models.CharField(max_length=2048),
        ),
    ]
